// blockchain 
export const LOAD_BLOCKCHAIN_DATA = 'LOAD_BLOCKCHAIN_DATA';

// immigration
export const CREATE_IMMIGRATION_PORT = 'CREATE_IMMIGRATION_PORT';
export const UPDATE_TRAVEL_HISTORY = 'UPDATE_TRAVEL_HISTORY';

// government
export const PRELOAD_GOVERNMENT = 'PRELOAD_GOVERNMENT';
export const CREATE_GOVERNMENT = 'CREATE_GOVERNMENT';
export const CREATE_PASSPORT = 'CREATE_PASSPORT';
export const RETRIEVE_TRAVEL_HISTORY = 'RETRIEVE_TRAVEL_HISTORY';

//hotel
export const CREATE_HOTEL = 'CREATE_HOTEL';